CREATE DATABASE Nixies2;

USE Nixies2;

CREATE TABLE Usuario
(
idusuario INT NOT NULL AUTO_INCREMENT,
nome VARCHAR(50) NOT NULL,
email VARCHAR(256) NOT NULL UNIQUE,
senha VARCHAR(40) NOT NULL,
PRIMARY KEY (idusuario)
);

CREATE TABLE Chat(
idusuario INT NOT NULL,
mensagem TEXT NOT NULL

);

ALTER TABLE Chat ADD CONSTRAINT fk_idusuario FOREIGN KEY (idusuario) REFERENCES Usuario (idusuario);


