CREATE DATABASE Nixies2;

USE Nixies2;

CREATE TABLE Usuario
(
idusuario INT NOT NULL AUTO_INCREMENT,
nome VARCHAR(50) NOT NULL,
email VARCHAR(256) NOT NULL UNIQUE,
senha VARCHAR(40) NOT NULL,
PRIMARY KEY (idusuario)
);

CREATE TABLE `nixies2`.`chat1` (
 `id` INT(11) NOT NULL AUTO_INCREMENT , 
 `mensagem` TEXT NOT NULL , 
 `from` VARCHAR(128) NOT NULL , 
 `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
 PRIMARY KEY (`id`)) ENGINE = InnoDB;

 CREATE TABLE `nixies2`.`chat2` ( 
`id` INT(11) NOT NULL AUTO_INCREMENT ,
`mensagem` TEXT NOT NULL , 
`from` VARCHAR(128) NOT NULL , 
`created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
 PRIMARY KEY (`id`)) ENGINE = InnoDB;

 CREATE TABLE `nixies2`.`chat3` (
`id` INT(11) NOT NULL AUTO_INCREMENT ,
 `mensagem` TEXT NOT NULL , 
 `from` VARCHAR(128) NOT NULL , 
 `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , 
 PRIMARY KEY (`id`)) ENGINE = InnoDB;

 CREATE TABLE `nixies2`.`chat4` (
 `id` INT(11) NOT NULL AUTO_INCREMENT , 
 `mensagem` TEXT NOT NULL , 
 `from` VARCHAR(128) NOT NULL , 
 `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , 
 PRIMARY KEY (`id`)) ENGINE = InnoDB;

 CREATE TABLE `nixies2`.`chat5` ( 
`id` INT(11) NOT NULL AUTO_INCREMENT , 
`mensagem` TEXT NOT NULL , 
`from` VARCHAR(128) NOT NULL , 
`created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , 
PRIMARY KEY (`id`)) ENGINE = InnoDB;



